require:
  - rubocop-rails
  - rubocop-capybara

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
